@startuml
'https://plantuml.com/sequence-diagram

class CommercialTenantContractApplicationForm{

    ContractApplicationFormStatusEnum status;
    ChargeTypeEnum chargeType;
    FundGatherModeEnum fundGatherMode;
    BigDecimal commissionCharge;
    ChargeMethodEnum chargeMethod;
    AccountInfo settlementAccountInfo;
    AccountInfo stagingAccountInfo;
    private CommercialTenantInfo commercialTenantInfo;
   void checkIfValid()
    void checkChargeMethodIfValid()
    void checkChargeTypeIfValid()
 completeCommercialTenantInfo(CommercialTenantInfo commercialTenantInfo)
}

class b{
String aa
}
CommercialTenantContractApplicationForm --* b
@enduml