server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.55.100.52:3306/xulingfeng?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: xulingfeng
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
