@startuml
'https://plantuml.com/sequence-diagram

autonumber
activate 商户
activate 平台
商户 -> 平台: 由柜面填写合约申请单,发起签约申请
平台 -> 平台: 校验申请单合法性
平台 -> 平台: 处理签约申请
平台 -> 商户: 返回合约详情和签约结果
deactivate 商户
activate 客户
客户 -> 平台: 由柜面填写合约申请单,发起签约申请(此处需绑定一个商户合约)
平台 -> 平台: 校验合约申请单合法性
平台 -> 平台: 处理签约申请单
平台 -> 客户: 返回合约详情和签约结果
deactivate 平台
deactivate 客户
@enduml